# permissions for end users to edit indexerclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: indexercluster-editor-role
rules:
- apiGroups:
  - enterprise.splunk.com
  resources:
  - indexerclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.splunk.com
  resources:
  - indexerclusters/status
  verbs:
  - get
