# permissions for end users to view indexerclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: indexercluster-viewer-role
rules:
- apiGroups:
  - enterprise.splunk.com
  resources:
  - indexerclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - enterprise.splunk.com
  resources:
  - indexerclusters/status
  verbs:
  - get
