# permissions for end users to edit searchheadclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: searchheadcluster-editor-role
rules:
- apiGroups:
  - enterprise.splunk.com
  resources:
  - searchheadclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.splunk.com
  resources:
  - searchheadclusters/status
  verbs:
  - get
