kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha4
featureGates:
  # any feature gate can be enabled here with "Name": true
  # or disabled here with "Name": false
  # not all feature gates are tested, however
  "CSIMigration": true
networking:
  ipFamily: ipv6
  apiServerAddress: 127.0.0.1
nodes:
- role: control-plane
  #image: kindest/node:v1.14.3