apiVersion: enterprise.splunk.com/v4
kind: LicenseManager
metadata:
  name: lm-example
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  volumes:
    - name: licenses
      configMap:
        name: splunk-licenses
  licenseUrl: /mnt/licenses/enterprise.lic
---
apiVersion: enterprise.splunk.com/v4
kind: ClusterManager
metadata:
  name: cm-example
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  licenseManagerRef:
    name: lm-example
  appRepo:
    appsRepoPollIntervalSeconds: 600
    defaults:
      volumeName: volume_app_repo
      scope: cluster
    appSources:
      - name: idxApps
        location: <apps-location>
    volumes:
      - name: volume_app_repo
        storageType: blob
        provider: azure
        path: <apps-path>
        endpoint: https://<apps-endpoint>
        secretRef: azure-blob-secret
---
apiVersion: enterprise.splunk.com/v4
kind: IndexerCluster
metadata:
  name: idxc-example
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  replicas: <n>
  clusterManagerRef:
    name: cm-example
  licenseManagerRef:
    name: lm-example
---
apiVersion: enterprise.splunk.com/v4
kind: SearchHeadCluster
metadata:
  name: shc-example
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  clusterManagerRef:
    name: cm-example
  licenseManagerRef:
    name: lm-example
  appRepo:
    appsRepoPollIntervalSeconds: 600
    defaults:
      volumeName: volume_app_repo
      scope: cluster
    appSources:
      - name: shApps
        location: <apps-location>
    volumes:
      - name: volume_app_repo
        storageType: blob
        provider: azure
        path: <apps-path>
        endpoint: https://<apps-endpoint>
        secretRef: azure-blob-secret
