apiVersion: enterprise.splunk.com/v4
kind: ClusterManager
metadata:
  name: cm-example
  finalizers:
  - enterprise.splunk.com/delete-pvc
---
apiVersion: enterprise.splunk.com/v4
kind: IndexerCluster
metadata:
  name: idxc-example
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  replicas: 3
  clusterManagerRef:
    name: cm-example
